- name: Upload apps to appetize
  # You may pin to the exact commit or the version.
  # uses: DrewCarlson/github-action-appetize@966ca0a334b28290435df80fda8e9bd24ad90aa9
  uses: DrewCarlson/github-action-appetize@v1.0.0
  with:
    # API token for appetize
    APPETIZE_TOKEN: 
    # App public key for update.
    PUBLICKEY: # optional, default is 
    # App file url
    FILE_URL: 
    # App platform (ios or android)
    PLATFORM: # default is android
